server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parg
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true