server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.zqgwhebbtugznmlvmaqf&password=@KiranSR99
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: file:D:/PARG/, file:/home/user/PARG/, file:/Users/PARG/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  filepath:
    windows: D:\\PARG\\
    linux: /home/user/PARG/
    mac: /Users/PARG/